# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

env:
  GEMINI_API_KEY: ${GEMINI_API_KEY}
prompts:
  - file://prompt_9.txt
  

providers:
  - "google:gemini-2.5-flash"
  - "google:gemini-2.5-flash-lite"
  

tests:
  assert:
      - type: contains
        value: <html>
      - type: contains
        value: <body>

      - type: regex
        value: "type\\s*=\\s*\"(email|text)\""
      - type: regex
        value: "type\\s*=\\s*\"password\""
      - type: regex
        value: "type\\s*=\\s*\"submit\""

      - type: icontains
        value: "<style"
      - type: icontains
        value: "display"
      - type: regex
        value: "@media\\s*\\("

      - type: regex
        value: "addEventListener\\s*\\(\\s*['\"]submit['\"]"

