# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

env:
  GEMINI_API_KEY: ${GEMINI_API_KEY}
prompts:
  - file://prompt_17.txt
  

providers:
  - "google:gemini-2.5-flash"
  - "google:gemini-2.5-flash-lite"

tests:

    assert:
      
    - type: regex
      value: "create\\s*<.*>\\s*\\("
    - type: regex
      value: "set\\s*\\("
    - type: regex
      value: "(currentQuestion|currentIndex|questionIndex)"
    
    - type: contains
      value: "correct_answer"
